allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  msgpackr-extract: true
  redis-memory-server: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@ronits2407/cp-api@1.0.8"
overrides:
  UnifiedAPI: link:../UnifiedAPI
